navsat_transform_node:
  ros__parameters:
    frequency: 30.0  # Match GPS update rate (1-10Hz typical)
    use_sim_time: true
    
    # Coordinate System Settings
    magnetic_declination_radians: 0.20  # Adjust for your location (Sydney: 11.5° ≈ 0.2 rad)
    yaw_offset: 0.0  # Add if GPS/IMU are misaligned
    zero_altitude: true  # Set first GPS altitude as zero
    
    # Frame Configuration
    world_frame: "odom"  # Must match EKF's world_frame
    base_link_frame: "base_link"
    child_frame_id: "base_link"
    publish_tf: True
    imu_frame: wam-v/base_link/imu_sensor
    gps_frame: wam-v/base_link/navsat_sensor

    # GPS Processing
    delay: 0.0  # Compensate for GPS latency (seconds)
    use_odometry_yaw: false  # Use EKF's yaw (more accurate than GPS course)
    broadcast_utm_transform: true
    publish_filtered_gps: true
    
    # Covariance Overrides (since Gazebo provides zeros)
    gps_pose_covariance: [9.0, 0.0, 0.0,
                          0.0, 9.0, 0.0,
                          0.0, 0.0, 25.0]  # [x, y, z] variances (m²)
